### ISSUE TITLE
A question about zk snarks

### ISSUE THREAD

**Issue by pkopparla** [ventali/awesome-zk#14]
Hello Ventali,

Thanks for the very nice repo with so many explanations. I had a question about https://github.com/ventali/awesome-zk/tree/main/zk-intro
I somewhat understand generating polynomials by fitting zeros and ones to the left, right and output values of computations. And then for the zero knowledge part, you have to do encryptions of the form
$$ E(v) = g^v mod(n) $$
where this stuff only works on integers. However, the coefficients of the fitted polynomials are often floats. What should I do here to encrypt them? Rounding the floats to integers before encryption introduces errors that are too large and none of the papers seem to discuss this case.

**Comment by ventali** [comment]
Hi, I will get back to you tonight. You are welcome to join our ZKP discussion group chat and ask the question there as well.
Here is the link: https://t.me/+gucKN1RBchMxMjVh

**Comment by pkopparla** [comment]
Awesome, thank you. I will post my question there with a little more context. Should I close the issue here?
